---
- name: Crate Linode vm for microk8s
  hosts: localhost
  vars_files:
    - ./group_vars/vars.yaml
  tasks:
    - name: Create microk8s-master-1
      linode.cloud.instance:
        label: microk8s-master-1
        region: ap-south
        type: g6-standard-2
        image: linode/ubuntu22.04
        tags: microk8s
        authorized_keys: "{{ public_key }}"
        state: present

    - name: Create microk8s-master-2
      linode.cloud.instance:
        label: microk8s-master-2
        region: ap-south
        type: g6-standard-2
        image: linode/ubuntu22.04
        tags: microk8s
        authorized_keys: "{{ public_key }}"
        state: present

    - name: Create microk8s-master-3
      linode.cloud.instance:
        label: microk8s-master-3
        region: ap-south
        type: g6-standard-2
        image: linode/ubuntu22.04
        tags: microk8s
        authorized_keys: "{{ public_key }}"
        state: present

    - name: Create microk8s-node-1
      linode.cloud.instance:
        label: microk8s-node-1
        region: ap-south
        type: g6-standard-2
        image: linode/ubuntu22.04
        tags: microk8s
        authorized_keys: "{{ public_key }}"
        state: present
      register: linode_instance

    - name: Create microk8s-node-2
      linode.cloud.instance:
        label: microk8s-node-2
        region: ap-south
        type: g6-standard-2
        image: linode/ubuntu22.04
        tags: microk8s
        authorized_keys: "{{ public_key }}" 
        state: present

    - name: Create microk8s-node-3
      linode.cloud.instance:
        label: microk8s-node-3
        region: ap-south
        type: g6-standard-2
        image: linode/ubuntu22.04
        authorized_keys: "{{ public_key }}"
        tags: microk8s
        state: present