---
- name: Get ssh key
  hosts: localhost
  tasks:
    - name: List all of the Linode ssh keys
      linode.cloud.ssh_key_list: {}
      register: linode_ssh_keys
    - name: Show to console 
      ansible.builtin.debug:
        var: linode_ssh_keys